export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GEt_ORDER_BY_ID_REQUEST = "GEt_ORDER_BY_ID_REQUEST";
export const GEt_ORDER_BY_ID_SUCCESS = "GEt_ORDER_BY_ID_SUCCESS";
export const GEt_ORDER_BY_ID_FAILURE = "GEt_ORDER_BY_ID_FAILURE";